name: Github Actions Example

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm test